### ISSUE TITLE
About Danboo Region Dataset download

### ISSUE THREAD

**Issue by UdonDa** [lllyasviel/DanbooRegion#1]
Thank you for sharing your dataset.

But, I can not unzip files that are downloaded from google drive https://drive.google.com/drive/folders/1ihLt6P7UQRlaFtZUEclXkWC9grmEXEUK?usp=sharing

I try on Ubuntu18.04 and Mac, but fail unzip on both environments.

```
❯ unzip DanbooRegion2020.zip.077
Archive:  DanbooRegion2020.zip.077
fatal error: read failure while seeking for End-of-centdir-64 signature.
  This zipfile is corrupt.
unzip:  cannot find zipfile directory in one of DanbooRegion2020.zip.077 or
        DanbooRegion2020.zip.077.zip, and cannot find DanbooRegion2020.zip.077.ZIP, period.
```

Thanks.

**Comment by lllyasviel** [comment]
ZIP and multipart ZIP are different, e.g., 

https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux

Thank you for your attention on this project.

**Comment by UdonDa** [comment]
Actually, I can get `DanbooRegion2020.zip`, but it cannot be unziped.

```
>file DanbooRegion2020.zip
DanbooRegion2020.zip: Zip archive data, at least v2.0 to extract

>unzip DanbooRegion2020.zip
Archive:  DanbooRegion2020.zip
fatal error: read failure while seeking for End-of-centdir-64 signature.
  This zipfile is corrupt.
unzip:  cannot find zipfile directory in one of DanbooRegion2020.zip or
        DanbooRegion2020.zip.zip, and cannot find DanbooRegion2020.zip.ZIP, period.
```

It works well.
```
zip -FF xx.zp --out xx_ff.zip
unzip xx_ff.zip
```

Thanks

**Comment by lllyasviel** [comment]
So do you still have problems?

**Comment by UdonDa** [comment]
No, I can see the dataset!
Thanks!!
