### ISSUE TITLE
Cannot load model using code

### ISSUE THREAD

**Issue by EightBitRG** [lllyasviel/DanbooRegion#6]
After installing all the dependencies, I get an error stating this:

UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
begin load

and then it cuts off and closes the program.

I made sure to version match to all the python dependencies and am currently using python 3.6 on a virtual environment created by python on windows 10 with a Geforce GTX 1070 TI

The full cmd prompt looks like this:

(venv) C:\Users\User\Downloads\DanbooRegion-master2\DanbooRegion-master\code>python segment.py emilia.jpg
Using TensorFlow backend.
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\User\Downloads\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2021-06-11 13:52:13.410991: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2021-06-11 13:52:13.649483: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: NVIDIA GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 7.05GiB
2021-06-11 13:52:13.649679: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
C:\Users\User\Downloads\venv\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
begin load

**Comment by EightBitRG** [comment]
After trying to load it on a cpu based tensor I get this:

2021-06-11 14:30:52.102708: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 578813952 exceeds 10% of system memory.
2021-06-11 14:30:52.730804: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 771751936 exceeds 10% of system memory.
2021-06-11 14:30:53.033104: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 1157627904 exceeds 10% of system memory.
2021-06-11 14:30:57.779650: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 578813952 exceeds 10% of system memory.
2021-06-11 14:30:58.372595: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 771751936 exceeds 10% of system memory.



Does this mean I do not have enough resources to run this?

**Comment by EightBitRG** [comment]
same thing If I upgrade to tensorflow 1.15 and run it using the gpu

**Comment by lllyasviel** [comment]
I am also using a GPU with 8GB memory and it is OK. I do not know what happens and I will look into this a bit.
What versions of tf have you tried?

**Comment by EightBitRG** [comment]
I've tried Tensorflow_gpu==1.5.0, Tensorflow_gpu==1.15.0, Tensorflow_gpu==1.15.0, Tensorflow_cpu==1.15.0, Tensorflow-cpu==1.15.0,Tensorflow==2.0.0, and I tried messing with trying to update some function calls with Tensorflow 2.5.0 on the most updated software, but after the 15th bug fix getting nowhere near as close to running the code as just using the outdated software I kind of gave up

For the GPU the most success I had was using Tensorflow_gpu==1.15.0 though it did give me a lot of depreciated warnings

though the Tensorflow_gpu 1.15.0 seems to want to  use my cpu instead: after a small bit of fiddling I added

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

to ignore the future depreciations and the cmd console output is downsized to this if this helps at all:

(venv) C:\Users\User\Downloads\DanbooRegion-master\code>python segment.py emilia.jpg
Using TensorFlow backend.
2021-06-12 14:09:39.381130: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2021-06-12 14:09:39.601199: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: NVIDIA GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 7.05GiB
2021-06-12 14:09:39.601441: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: NVIDIA GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
C:\Users\User\Downloads\venv\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
begin load

(venv) C:\Users\User\Downloads\DanbooRegion-master\code>

**Comment by lllyasviel** [comment]
Today, I tried several different laptops and PCs but I cannot reproduce this. Are there anyone else also has this problem? It looks that your 1070 Ti has some memory issues but I have tried GPUs with even smaller memory but still I cannot encounter your problem....

**Comment by EightBitRG** [comment]
Huh... Maybe I'll try rebuilding everything on my laptop

**Comment by EightBitRG** [comment]
Does it give you the error that the training configuration was not loaded on those devices?

**Comment by EightBitRG** [comment]
Weirdly enough I got it to run on my laptop that is really outdated... So I guess it could be a problem with my Cuda and Cudnn setup?

**Comment by lllyasviel** [comment]
well anyway welcome to the buggy world of TENSORFLOW



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 18, 2021 00:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lllyasviel/DanbooRegion] Cannot load model using code (#6)




 
Weirdly enough I got it to run on my laptop that is really outdated... So I guess it could be a problem with my Cuda and Cudnn setup?

**Comment by EightBitRG** [comment]
Yeah... I've started to find that out :P I'm thinking I'm going to try learning pytorch due to the depreciation from version to version of tensorflow. Maybe if I can find out how to use it more I'll even try to convert this code to pytorch... Though I'll be honest I'm a complete newbie to machine learning

**Comment by EightBitRG** [comment]
Huh, after copying the code from my laptop to my computer I was able to get it to run...
Machine Learning is weird
